# Generated by Django 5.1.4 on 2025-01-29 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='<No name provided>', max_length=255, verbose_name='Service')),
                ('rate', models.IntegerField(blank=True, default=0, null=True, verbose_name='Rate')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NULL', max_length=255, verbose_name='Staff Name')),
                ('contact', models.IntegerField(blank=True, null=True, verbose_name='Contact Number')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Salary')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='Anonymous', max_length=255, null=True, verbose_name='Customer Name')),
                ('contact', models.IntegerField(blank=True, null=True, verbose_name='Contact Number')),
                ('is_repeat_customer', models.BooleanField(default=False, verbose_name='Repeat Customer')),
                ('transaction_cost', models.IntegerField(default=0, null=True, verbose_name='Total Amount')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('services', models.ManyToManyField(related_name='transactions', to='app.service')),
                ('serving_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.staff')),
            ],
        ),
    ]
